name: DMAI-Assignment 2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - torchvision
  - pip:
      - opencv-python
      - imageio
      - torchvision
      - torchaudio
      - optuna

